### ISSUE TITLE
Error in main lua adv_weapons a nil value

### ISSUE THREAD

**Issue by Mathiaszero** [appgurueu/adv_weapons#2] opened 2021-01-04 18:53 UTC
ModError: Failed to load and run script from D:\Portal\New Program Files\Games\minetest-5.3.0_dedicatedTest\bin\..\mods\adv_weapons\init.lua:
...est-5.3.0_dedicatedTest\bin\..\mods\adv_weapons/main.lua:1: attempt to index global 'adv_weapons' (a nil value)
stack traceback:
	...est-5.3.0_dedicatedTest\bin\..\mods\adv_weapons/main.lua:1: in main chunk
	...\minetest-5.3.0_dedicatedTest\bin\..\mods\modlib/mod.lua:11: in function 'include_env'
	...\minetest-5.3.0_dedicatedTest\bin\..\mods\modlib/mod.lua:29: in function 'extend'
	...est-5.3.0_dedicatedTest\bin\..\mods\adv_weapons\init.lua:2: in main chunk
Check debug.txt for details.

I am using 5.3.0, it crashed right after I hit connect. I have all dependencies installed. Thanks in advance.

**Comment by appgurueu** [comment] 2021-01-04 19:09
Cannot reproduce. Try upgrading modlib.

**Comment by Mathiaszero** [comment] 2021-01-05 03:47
![image](https://user-images.githubusercontent.com/55817193/103604064-12cc0980-4ede-11eb-9f77-e3cf8fcee75b.png)
![image](https://user-images.githubusercontent.com/55817193/103604124-31ca9b80-4ede-11eb-8394-9bd2d104e360.png)

So I removed and re-added/upgraded the two mods by downloading from Content DB the latest versions, and I get the same error. If you can give me about a week I can work to see if other versions have the same issue or try a different minetest build. Otherwise unfortunately it really is just me and I will have to move on.

In the meantime I do want to note that without advanced weapons active, modlib does not produce any errors and my game is running normally. Conversely, if advanced weapons is active and modlib is inactive, my game is also running normally. Somehow the two mods do not seem to like each other.

**Comment by Mathiaszero** [comment] 2021-01-06 16:08
After tinkering around, I ended up downgrading to rolling 14 of modlib; paired with your latest version of adv_weapons, the mods finally worked together. I had happened to skim through the forum and a user was talking about the mod in its working state which was about that time. I guess case is closed now, I appreciate your patience. Another reason it is nice Github allows you to look for previous versions with ease. Not the best fix, but at least no more crashes.

**Comment by appgurueu** [comment] 2021-02-04 23:08
@Mathiaszero fixed by https://github.com/appgurueu/adv_weapons/commit/dd1e7932e959a076dd11034fb4336e7575e2c509

**Closed as completed by appgurueu** 2021-02-04 23:08 UTC
Labels: bug, invalid

**Comment by PavanLuca** [comment] 2023-12-13 18:00
So now everyone should just downgrade modlib to make it work? Because I have it from version 5.7.0 and now it still makes the worlds crash at 5.8.0.
